// Read .env and generate frontend/.env + Capacitor config + api-config.js
const fs = require('fs');
const path = require('path');

function parseEnv(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const env = {};
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx > 0) env[trimmed.slice(0, idx)] = trimmed.slice(idx + 1);
  });
  return env;
}

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');

if (!fs.existsSync(envPath)) {
  console.error('No .env file found. Copy .env.example to .env first.');
  process.exit(1);
}

const env = parseEnv(envPath);

const appBaseUrl = (env.APP_BASE_URL || 'http://localhost:5173').replace(/\/$/, '');
const viteBase = env.VITE_BASE || '/';
const useRemote = env.CAPACITOR_REMOTE === 'true';
const isHttps = appBaseUrl.startsWith('https');

// Full Capacitor URL: APP_BASE_URL + VITE_BASE
const capUrl = useRemote ? appBaseUrl + viteBase : '';

// Generate capacitor.config.json
const config = {
  appId: 'com.skateboard.shop',
  appName: '地面飞行滑板',
  webDir: 'dist',
  server: useRemote ? {
    url: capUrl,
    cleartext: !isHttps,
    androidScheme: isHttps ? 'https' : 'http',
    iosScheme: isHttps ? 'https' : 'http',
  } : {
    cleartext: !isHttps,
    androidScheme: isHttps ? 'https' : 'http',
    iosScheme: isHttps ? 'https' : 'http',
  },
};

const configPath = path.join(root, 'packages', 'frontend', 'capacitor.config.json');
fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
console.log('Generated: capacitor.config.json');
console.log('  URL:', useRemote ? capUrl : '(local mode)');

// Generate api-config.js: APP_BASE_URL + VITE_BASE + api
const apiConfigUrl = appBaseUrl + viteBase + 'api';
const apiConfig = `// Auto-generated by sync-config.cjs — do not edit
window.__API_BASE__ = "${apiConfigUrl}";
`;

const apiConfigPath = path.join(root, 'packages', 'frontend', 'public', 'api-config.js');
fs.writeFileSync(apiConfigPath, apiConfig);
console.log('Generated: public/api-config.js');
console.log('  __API_BASE__:', apiConfigUrl);

// Generate frontend .env from root configs
const appHost = new URL(appBaseUrl).hostname;
const frontendEnv = `# Auto-generated by sync-config.cjs — do not edit
VITE_BASE=${viteBase}
ALLOWED_HOSTS=.ngrok-free.dev,.ngrok-free.app,${appHost}
`;
const frontendEnvPath = path.join(root, 'packages', 'frontend', '.env');
fs.writeFileSync(frontendEnvPath, frontendEnv);
console.log('Generated: packages/frontend/.env');
console.log('  VITE_BASE:', viteBase);
