// Read .env and generate Capacitor + other configs
const fs = require('fs');
const path = require('path');

function parseEnv(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const env = {};
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const idx = trimmed.indexOf('=');
    if (idx > 0) {
      env[trimmed.slice(0, idx)] = trimmed.slice(idx + 1);
    }
  });
  return env;
}

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');

if (!fs.existsSync(envPath)) {
  console.error('No .env file found. Run npm run start first.');
  process.exit(1);
}

const env = parseEnv(envPath);

// Generate capacitor.config.json
const url = env.CAPACITOR_URL;
const useRemote = !!url;
const config = {
  appId: 'com.skateboard.shop',
  appName: '地面飞行滑板',
  webDir: 'dist',
  ...(useRemote ? {
    server: {
      url: url.replace(/\/$/, ''),
      cleartext: !url.startsWith('https'),
      androidScheme: url.startsWith('https') ? 'https' : 'http',
    },
  } : {}),
};

// Write capacitor.config.json
const configPath = path.join(root, 'packages', 'frontend', 'capacitor.config.json');
fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
console.log('Generated: capacitor.config.json');
console.log('  URL:', config.server.url);

// Generate API config for frontend (used when Capacitor runs in local mode)
const apiBase = env.API_BASE_URL || `/api`;
const apiConfig = `// Auto-generated by sync-config.cjs — do not edit
window.__API_BASE__ = "${apiBase.replace(/\/$/, '')}";
`;

const apiConfigPath = path.join(root, 'packages', 'frontend', 'public', 'api-config.js');
fs.writeFileSync(apiConfigPath, apiConfig);
console.log('Generated: public/api-config.js');
console.log('  API:', apiBase);
